"""Create team_members table

Revision ID: 0001
Revises: 
Create Date: 2025-09-09 10:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Check if table already exists (idempotent migration)
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'team_members' not in inspector.get_table_names():
        op.create_table('team_members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('role', sa.String(length=100), nullable=False),
        sa.Column('profilePicture', sa.String(length=255), nullable=False, server_default='/img/fallback-knowit.png'),
        sa.Column('linkedinUrl', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('1')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    # ### end Alembic commands ###